name:
  viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
  robots: 'index, follow'
  description: 'The Neverending Exploration is an index to keep myself learning something new and useful everyday'
  keywords: 'dindasigma, dinda sigmawaty, the neverending exploration'
  author: 'dindasigma'
og:
  type: 'website'
  title: 'The Neverending Exploration'
  url: 'https://neverending.dindasigma.com/'
  description: 'The Neverending Exploration is an index to keep myself learning something new and useful everyday'
  site-name: 'The Neverending Exploration'
  image: '/img/logo.jpg'
    type: 'image/png'
    width: '101'
    height: '101'